version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      jjwt:
        patterns:
          - "io.jsonwebtoken:*"
      backend-minor-and-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "io.jsonwebtoken:*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directory: "/sgfl-frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/sgfl-frontend"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
