# Base de dados H2 (Totalmente local e em memória)
spring.datasource.url=jdbc:h2:mem:sgfdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 (acesso em http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Hibernate / JPA (cria as tabelas na memória)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Desativar o Flyway para não procurar o PostgreSQL
spring.flyway.enabled=false

# Configurações de JWT e Rate Limit
jwt.secret=SgflLogiTechChaveSecretaMuitoSeguraParaAssinaturaDoTokenJWT123456
jwt.expiration-ms=86400000

ratelimit.enabled=true
ratelimit.auth.capacity=15
ratelimit.auth.tokens-per-minute=15
ratelimit.api.capacity=120
ratelimit.api.tokens-per-minute=120